### ISSUE TITLE
CSRF token not being sent automatically

### ISSUE THREAD

**Issue by MichaelNZ85** [inertiajs/inertia-django#14]
I'm at my wits' end trying to get Django to send the CSRF token to the backend (project [here](https://github.com/MichaelNZ85/django-inertia-test)).

The CSRF token is being sent in the cookie, but I cannot set an `X-XSRF-Token`  header as a global header on Axios. 

Would it be possible to include this by default in inertia-django, like the Laravel implementation already does?

**Comment by BrandonShar** [comment]
Hey @MichaelNZ85, I took a look at your last commit and you're nearly there!

In your `main.js` add the following lines:
```js
axios.defaults.xsrfHeaderName = "X-CSRFToken"
axios.defaults.xsrfCookieName = "csrftoken"
```

and then on your login view or any unauthenticated forms, add the following decorator:
```python
from django.views.decorators.csrf import ensure_csrf_cookie

@ensure_csrf_cookie
@inertia('YourComponent')
def your_view(request):
  pass
```

> Would it be possible to include this by default in inertia-django, like the Laravel implementation already does?

We're discussing this internally now, but I haven't come up with anything I really like yet. There's an important distinction here that the Laravel Inertia adapter **does not** automatically handle CSRF, the Laravel framework itself does, so it's a non-issue for that adapter. I _think_ it makes sense to automatically handle CSRF somehow since it's in such contrast to how Django wants it to work, but I want to make sure we do that in a way that doesn't conflict with the Django framework itself.

**Comment by MichaelNZ85** [comment]
I tried that and still no luck. I've messaged the creator of [the template I was using](https://github.com/mercuryseries/django-inertia-vue), but he hasn't replied as of yet.

I think it would be great if the actual Inertia framework handled the CSRF token.

**Comment by BrandonShar** [comment]
Using `@ensure_csrf_cookie` didn't work? It's possible there's a different issue here.
> I think it would be great if the actual Inertia framework handled the CSRF token.

Yes, I agree; I've come around on this after talking to a few people. I'll get this added!
